parameters:
  netzmacht.contao_packagist_package.package_json_url: 'https://packagist.org/packages/%%s.json'
  netzmacht.contao_packagist_package.cache.lifetime:  86400

  netzmacht.contao_packagist_package.fields:
    - name
    - description
    - version
    - type
    - favers
    - downloads_total
    - time
    - date
    - repository
